added linter as dependency

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -7,14 +7,14 @@ npx lint-staged
 echo "\\n❯ Running Build Checks"
 npm run build > /dev/null
 status=$?
-[ $status -eq 0 ] && echo -e "\e[1;42m \\nSuccessful ✔ \\n \e[0m" || echo -e "\e[1;31m Build failed ✖\\n \e[0m"
+[ $status -eq 0 ] && echo "\\nSuccessful ✔ \\n" || echo "> Build failed ✖\\n"
 
 echo "❯ Checking for broken links"
 npx npm-run-all -p -r start blc
 status=$?
-[ $status -eq 0 ] && echo -e "\e[1;42m \\nSuccessful ✔\\n \e[0m" || echo -e "\e[1;31m BLC check failed ✖\\n \e[0m"
+[ $status -eq 0 ] && echo "\\nSuccessful ✔\\n" || echo "> BLC check failed ✖\\n"
 
 echo "❯ Checking for Spelling erros"
 npm run cspell
 status=$?
-[ $status -eq 0 ] && echo -e "\e[1;42m  \\nSuccessful ✔\\n \e[0m" || echo -e "\e[1;31m Spelling errors ✖\\n \e[0m"
+[ $status -eq 0 ] && echo "\\nSuccessful ✔\\n" || echo "> Spelling errors ✖\\n"
