added cspell

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,15 +1,20 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-echo "Linting Staged Files\\n"
+echo "❯ Linting Staged Files\\n"
 npx lint-staged
 
-echo "\\nRunning Build Checks\\n"
+echo "\\n❯ Running Build Checks"
 npm run build > /dev/null
 status=$?
-[ $status -eq 0 ] && echo " - Build was successful ✓\\n" || echo " - Build failed ✕\\n"
+[ $status -eq 0 ] && echo "Successful ✔ \\n" || echo "> Build failed ✖\\n"
 
-echo "Checking for broken links"
+echo "❯ Checking for broken links"
 npx npm-run-all -p -r start blc
 status=$?
-[ $status -eq 0 ] && echo " - No Broken Links ✓\\n" || echo " - BLC check failed ✕\\n"
+[ $status -eq 0 ] && echo "Successful ✔\\n" || echo "> BLC check failed ✖\\n"
+
+echo "❯ Checking for Spelling erros"
+npm run cspell
+status=$?
+[ $status -eq 0 ] && echo "Successful ✔\\n" || echo "> Spelling errors ✖\\n"
